--1.2
alter table SANPHAM add GHICHU varchar(20)
--1.3
alter table KHACHHANG add LOAIKH tinyint
--1.4
alter table SANPHAM alter column GHICHU varchar(100)
--1.5
alter table SANPHAM drop column GHICHU
--1.6
alter table KHACHHANG alter column LOAIKH varchar(20)
--1.7
alter table SANPHAM add constraint DVT check(DVT='cay' OR DVT='hop' OR DVT='cai' OR DVT='quyen' OR DVT='chuc')
--1.8
alter table CTHD alter column SOHD int NOT NULL
alter table CTHD alter column MASP char(4) NOT NULL
alter table CTHD add constraint CTHD primary key (SOHD,MASP)
alter table SANPHAM add constraint C_GIABAN check(GIA>=500)
--1.9 
alter table CTHD add constraint C_SLMUA check (SL>0)
--1.10
alter table KHACHHANG add constraint C_NGDK_NGSINH check(NGDK>NGSINH)
--3.1
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NUOCSX = 'Trung Quoc'
--3.2 
SELECT MASP , TENSP
FROM SANPHAM
WHERE DVT IN ('cay','quyen')
--3.3
select masp,tensp from SANPHAM where masp like 'B%01'
--3.4
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000
--3.5
SELECT MASP,TENSP
FROM SANPHAM
WHERE (NUOCSX ='Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000
-- 3.6
SELECT SOHD,TRIGIA
FROM HOADON
WHERE NGHD IN ('01/01/2007','02/01/2007')
-- 3.7
SELECT SOHD,TRIGIA , NGHD
FROM HOADON
WHERE YEAR(NGHD) = '2007' AND MONTH(NGHD) = '01'
ORDER BY NGHD ASC , TRIGIA DESC
--3.8
SELECT A.MAKH , HOTEN 
FROM KHACHHANG A, HOADON B
WHERE A.MAKH = B.MAKH AND NGHD = '1/1/2007'
-- 3.9
SELECT SOHD , TRIGIA 
FROM HOADON A , NHANVIEN B
WHERE A.MANV = B.MANV AND HOTEN = 'Nguyen Van B' AND NGHD = '10/28/2006'
-- 3.10
SELECT SANPHAM.MASP , TENSP
FROM (KHACHHANG JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH) JOIN ( SANPHAM JOIN CTHD ON SANPHAM.MASP = CTHD.MASP ) ON HOADON.SOHD = CTHD.SOHD
WHERE HOTEN = 'Nguyen Van A' AND MONTH(NGHD)= 10 AND YEAR(NGHD) = 2006
-- 3.11
SELECT SOHD 
FROM CTHD
WHERE MASP ='BB01' OR MASP = 'BB02'
-- 3.12
SELECT SOHD 
FROM CTHD
WHERE ( MASP ='BB01' OR MASP = 'BB02' ) AND SL BETWEEN 10 AND 20
-- 3.13
SELECT SOHD
FROM CTHD A
WHERE MASP = 'BB02' AND A.SL BETWEEN 10 AND 20 AND EXISTS (
	SELECT SOHD 
	FROM CTHD B
	WHERE MASP = 'BB01' AND A.SOHD = B.SOHD AND B.SL BETWEEN 10 AND 20
	)
-- 3.14
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NUOCSX ='Trung Quoc'
UNION
SELECT SANPHAM.MASP , TENSP
FROM (HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NGHD = '1/1/2007'
-- 3.15

SELECT A.MASP , TENSP
FROM SANPHAM A
WHERE NOT EXISTS (
	SELECT MASP
	FROM CTHD B
	WHERE A.MASP = B.MASP
	)
-- 3.16
SELECT S.MASP , TENSP
FROM SANPHAM S
WHERE NOT EXISTS(
	SELECT MASP
	FROM CTHD H JOIN HOADON A ON H.SOHD = A.SOHD
	WHERE S.MASP = H.MASP AND YEAR(A.NGHD) = 2006
	) 

-- 3.17
SELECT S.MASP , TENSP
FROM SANPHAM S
WHERE NUOCSX = 'Trung Quoc' AND NOT EXISTS (
	SELECT MASP
	FROM CTHD H JOIN HOADON A ON H.SOHD = A.SOHD
	WHERE S.MASP = H.MASP AND YEAR(A.NGHD) = 2006
	)

-- 3.18
SELECT SOHD
FROM HOADON 
WHERE NOT EXISTS ( 
			SELECT MASP
			FROM SANPHAM
			WHERE NUOCSX= 'Singapore' AND NOT EXISTS (
				SELECT SOHD
				FROM CTHD 
				WHERE HOADON.SOHD = CTHD.SOHD AND CTHD.MASP = SANPHAM.MASP) )
-- 3.19
SELECT A.SOHD ,SOLAN
FROM HOADON A JOIN (SELECT MIN(SL) SOLAN 
					FROM HOADON HD JOIN (
							SELECT HOADON.SOHD , COUNT(*) SL
							FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP =CTHD.MASP 
							WHERE NUOCSX = 'Singapore' AND YEAR(NGHD) = 2006 
							GROUP BY HOADON.SOHD) TABLE1 
								ON TABLE1.SOHD = HD.SOHD 
					) TABLE2 
						ON A.SOHD = TABLE2.SOLAN
SELECT  COUNT (*) AS SOLANMUA 
FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Singapore'  AND YEAR(NGHD) = 2006
-- 3.20
SELECT COUNT(*) AS N'Số Hóa Đơn'
FROM HOADON
WHERE MAKH IS NULL
-- 3.21 *
SELECT COUNT(DISTINCT MASP) AS N'Số Sản Phẩm'
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006
-- 3.22
SELECT MIN(TRIGIA) AS N'Giá Trị Thấp Nhất' , MAX (TRIGIA) AS N'Giá Trị Cao Nhất'
FROM HOADON
-- 3.23
SELECT AVG(TRIGIA) AS N'Trung Bình Hóa Đơn'
FROM HOADON
WHERE YEAR(NGHD) ='2006'
-- 3.24 
SELECT SUM(TRIGIA) AS N'Doanh Thu 2006'
FROM HOADON
SWHERE YEAR(NGHD) = 2006
-- 3.25
SELECT SOHD AS N'Hóa Đơn Có Giá Trị Cao Nhất'
FROM HOADON
SWHERE TRIGIA= (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD)=2006)
-- 3.26
SSELECT HOTEN AS N'Họ Tên KH'
SFROM HOADON JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
SWHERE TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR (NGHD)=2006)
-- 3.27
SSELECT TOP 3 MAKH , HOTEN
SFROM KHACHHANG
SORDER BY DOANHSO DESC
-- 3.28
SSELECT MASP ,TENSP
SFROM SANPHAM
SWHERE GIA IN (
	SSELECT TOP 3 GIA
	SFROM SANPHAM
	SORDER BY GIA DESC)
-- 3.29
SSELECT MASP , TENSP
SFROM SANPHAM
SWHERE NUOCSX = 'Thai Lan' AND GIA IN (
						SELECT TOP 3 GIA 
						--FROM SANPHAM 
						--ORDER BY GIA DESC )
-- 3.30
--SELECT MASP , TENSP
--FROM SANPHAM
--WHERE NUOCSX ='Trung Quoc' AND GIA IN (
									--SELECT TOP 3 GIA
									--FROM SANPHAM
									--WHERE NUOCSX ='Trung Quoc'
									--ORDER BY GIA DESC)
--3.32
--SELECT COUNT (*) AS SOSP
--FROM SANPHAM
--WHERE NUOCSX='Trung Quoc'
--3.33 
--SELECT NUOCSX , COUNT (*) AS SOSP
--FROM SANPHAM
--GROUP BY NUOCSX 
--3.34
--SELECT NUOCSX , MAX(GIA) AS GIACAONHAT , MIN(GIA) AS GIATHAPNHAT , AVG(GIA) AS GIATB
--FROM SANPHAM
--GROUP BY NUOCSX
--3.35
--SELECT NGHD , SUM(TRIGIA) AS DOANHTHU
--FROM HOADON
--GROUP BY NGHD
